services:
  db:
    environment:
      - MYSQL_ROOT_PASSWORD
    image: mysql:8.0
    network_mode: host
    restart: always
    volumes:
      - ./data-db:/var/lib/mysql

  site-a:
    depends_on:
      - db
    environment:
      - database__connection__database=site-a
      - database__connection__password=${MYSQL_ROOT_PASSWORD:?err}
      - server__port=2368
      - url=https://${GHOST_PUBLIC_URL_A:?err}
    image: ghost:5
    network_mode: host
    restart: always
    volumes:
      - ./data-site-a:/var/lib/ghost/content

  site-b:
    depends_on:
      - db
    environment:
      - database__connection__database=site-b
      - database__connection__password=${MYSQL_ROOT_PASSWORD:?err}
      - server__port=2369
      - url=https://${GHOST_PUBLIC_URL_B:?err}
    image: ghost:5
    network_mode: host
    restart: always
    volumes:
      - ./data-site-b:/var/lib/ghost/content
